"""Base strategy abstract class for signal generation."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal

import pandas as pd

from app.modules.signals.models import SignalType


@dataclass
class SignalData:
    """Data class for signal information generated by a strategy.

    This is an intermediate representation before creating the DB model.
    """

    symbol: str
    signal_type: SignalType
    strength: Decimal  # 0.0 to 1.0
    confidence: Decimal  # 0.0 to 1.0
    price_at_signal: Decimal
    entry_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    risk_reward_ratio: Decimal | None = None
    indicators: dict | None = None
    notes: str | None = None


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    All strategies must implement:
    - generate_signals(): Generate signals from OHLCV data
    - get_parameters(): Return configurable parameters

    Strategies receive historical OHLCV data and return a list of SignalData.
    """

    # Strategy metadata - override in subclasses
    name: str = "base"
    description: str = "Base strategy - do not use directly"
    default_timeframe: str = "1d"

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, symbol: str) -> list[SignalData]:
        """Generate trading signals from OHLCV data.

        Args:
            df: DataFrame with columns: Open, High, Low, Close, Volume
                Index should be datetime
            symbol: Stock symbol

        Returns:
            List of SignalData objects (usually 0 or 1 signals)
        """
        pass

    @abstractmethod
    def get_parameters(self) -> dict:
        """Return the strategy's configurable parameters.

        Returns:
            Dictionary of parameter names to their current values
        """
        pass

    def calculate_stop_loss(
        self,
        entry_price: Decimal,
        signal_type: SignalType,
        atr: Decimal | None = None,
        atr_multiplier: Decimal = Decimal("2"),
        fallback_pct: Decimal = Decimal("0.02"),
    ) -> Decimal:
        """Calculate stop loss price.

        Uses ATR-based stop loss if ATR is available,
        otherwise falls back to percentage-based.

        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            atr: Average True Range value (optional)
            atr_multiplier: Multiplier for ATR (default 2x)
            fallback_pct: Fallback percentage if no ATR (default 2%)

        Returns:
            Stop loss price
        """
        if atr:
            stop_distance = atr * atr_multiplier
        else:
            stop_distance = entry_price * fallback_pct

        if signal_type == SignalType.BUY:
            return entry_price - stop_distance
        else:  # SELL
            return entry_price + stop_distance

    def calculate_take_profit(
        self,
        entry_price: Decimal,
        stop_loss: Decimal,
        signal_type: SignalType,
        risk_reward_ratio: Decimal = Decimal("2"),
    ) -> Decimal:
        """Calculate take profit price based on risk/reward ratio.

        Args:
            entry_price: Entry price
            stop_loss: Stop loss price
            signal_type: BUY or SELL
            risk_reward_ratio: Target R:R ratio (default 2:1)

        Returns:
            Take profit price
        """
        risk = abs(entry_price - stop_loss)
        reward = risk * risk_reward_ratio

        if signal_type == SignalType.BUY:
            return entry_price + reward
        else:  # SELL
            return entry_price - reward

    def calculate_position_size(
        self,
        portfolio_value: Decimal,
        entry_price: Decimal,
        stop_loss: Decimal,
        risk_per_trade_pct: Decimal = Decimal("0.02"),
    ) -> int:
        """Calculate position size based on risk.

        Uses the formula: Position Size = (Portfolio * Risk%) / (Entry - SL)

        Args:
            portfolio_value: Total portfolio value
            entry_price: Entry price
            stop_loss: Stop loss price
            risk_per_trade_pct: Max risk per trade as decimal (default 2%)

        Returns:
            Number of shares to buy
        """
        risk_amount = portfolio_value * risk_per_trade_pct
        risk_per_share = abs(entry_price - stop_loss)

        if risk_per_share <= 0:
            return 0

        shares = int(risk_amount / risk_per_share)
        return max(0, shares)

    def _to_decimal(self, value) -> Decimal | None:
        """Convert value to Decimal, handling NaN."""
        if value is None or pd.isna(value):
            return None
        return Decimal(str(round(float(value), 4)))

