"""Screener database models."""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.database import Base


class CustomScreener(Base):
    """User-defined custom screener configuration."""

    __tablename__ = "custom_screeners"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    universe: Mapped[str] = mapped_column(String(50), nullable=False, default="nifty500")
    filters: Mapped[dict] = mapped_column(JSONB, nullable=False)
    min_score: Mapped[float] = mapped_column(Float, nullable=False, default=50.0)
    top_n: Mapped[int] = mapped_column(Integer, nullable=False, default=50)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    runs: Mapped[list["ScreenerRun"]] = relationship(
        "ScreenerRun", back_populates="custom_screener", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("ix_custom_screeners_user", "user_id"),
        Index("ix_custom_screeners_name", "user_id", "name"),
    )

    def __repr__(self) -> str:
        return f"<CustomScreener {self.name}>"


class ScreenerRun(Base):
    """Record of a screener execution."""

    __tablename__ = "screener_runs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    custom_screener_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("custom_screeners.id", ondelete="SET NULL"),
        nullable=True,
    )
    preset: Mapped[str | None] = mapped_column(String(50), nullable=True)
    universe: Mapped[str] = mapped_column(String(50), nullable=False)
    filters: Mapped[dict] = mapped_column(JSONB, nullable=False)
    min_score: Mapped[float] = mapped_column(Float, nullable=False)
    top_n: Mapped[int] = mapped_column(Integer, nullable=False)
    total_screened: Mapped[int] = mapped_column(Integer, nullable=False)
    passed_count: Mapped[int] = mapped_column(Integer, nullable=False)
    duration_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    executed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    custom_screener: Mapped["CustomScreener | None"] = relationship(
        "CustomScreener", back_populates="runs"
    )
    results: Mapped[list["ScreenerResultRecord"]] = relationship(
        "ScreenerResultRecord", back_populates="run", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("ix_screener_runs_user", "user_id"),
        Index("ix_screener_runs_executed", "executed_at"),
    )

    def __repr__(self) -> str:
        return f"<ScreenerRun {self.id[:8]}>"


class ScreenerResultRecord(Base):
    """Individual stock result from a screener run."""

    __tablename__ = "screener_results"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    run_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("screener_runs.id", ondelete="CASCADE"), nullable=False
    )
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    passed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    filter_scores: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    reasons: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    metadata: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Relationships
    run: Mapped["ScreenerRun"] = relationship("ScreenerRun", back_populates="results")

    __table_args__ = (
        Index("ix_screener_results_run", "run_id"),
        Index("ix_screener_results_symbol", "symbol"),
    )

    def __repr__(self) -> str:
        return f"<ScreenerResultRecord {self.symbol} rank={self.rank}>"


class DailyRecommendation(Base):
    """Daily stock recommendations generated by scheduled screeners.

    Categories:
    - momentum: Top momentum stocks
    - breakout: Potential breakout candidates
    - pullback: Pullback opportunities (value entry)
    - sector: Strong sector leaders
    """

    __tablename__ = "daily_recommendations"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)

    # Price data at recommendation time
    price_at_rec: Mapped[float] = mapped_column(Float, nullable=False)

    # Performance tracking fields (updated later)
    price_1d: Mapped[float | None] = mapped_column(Float, nullable=True)
    price_1w: Mapped[float | None] = mapped_column(Float, nullable=True)
    price_1m: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_1d: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_1w: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_1m: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Screener metadata
    filter_scores: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    reasons: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    metadata: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        Index("ix_daily_recommendations_date", "date"),
        Index("ix_daily_recommendations_date_category", "date", "category"),
        Index("ix_daily_recommendations_symbol", "symbol"),
    )

    def __repr__(self) -> str:
        return f"<DailyRecommendation {self.symbol} {self.category}>"

