"""Add trigger_price and related columns to orders

Revision ID: b4c844c2eb96
Revises: add_risk_tables
Create Date: 2025-12-21 17:18:55.383621+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c844c2eb96'
down_revision: Union[str, None] = 'add_risk_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create cost_lots table for FIFO tracking
    op.create_table('cost_lots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('trade_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_lots_fifo', 'cost_lots', ['user_id', 'symbol', 'purchased_at'], unique=False)
    op.create_index(op.f('ix_cost_lots_symbol'), 'cost_lots', ['symbol'], unique=False)
    op.create_index('ix_cost_lots_user_symbol', 'cost_lots', ['user_id', 'symbol'], unique=False)

    # Add trigger price and related columns to orders
    op.add_column('orders', sa.Column('trigger_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('orders', sa.Column('valid_till', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('parent_order_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('orders', sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_orders_open_trigger', 'orders', ['status', 'trigger_price'], unique=False)

    # Add SL/TP and sector to positions
    op.add_column('positions', sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('positions', sa.Column('take_profit', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('positions', sa.Column('sector', sa.String(length=50), nullable=True))
    op.create_index('ix_positions_user_sector', 'positions', ['user_id', 'sector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop positions columns
    op.drop_index('ix_positions_user_sector', table_name='positions')
    op.drop_column('positions', 'sector')
    op.drop_column('positions', 'take_profit')
    op.drop_column('positions', 'stop_loss')

    # Drop orders columns
    op.drop_index('ix_orders_open_trigger', table_name='orders')
    op.drop_column('orders', 'triggered_at')
    op.drop_column('orders', 'parent_order_id')
    op.drop_column('orders', 'valid_till')
    op.drop_column('orders', 'trigger_price')

    # Drop cost_lots table
    op.drop_index('ix_cost_lots_user_symbol', table_name='cost_lots')
    op.drop_index(op.f('ix_cost_lots_symbol'), table_name='cost_lots')
    op.drop_index('ix_cost_lots_fifo', table_name='cost_lots')
    op.drop_table('cost_lots')
    # ### end Alembic commands ###

