"""Signal data models for the trading system.

These are data classes for passing signal information between components.
Not database models - those remain in the backend.
"""

from dataclasses import dataclass
from decimal import Decimal
from enum import Enum


class SignalType(str, Enum):
    """Signal type enum."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class SignalData:
    """Data class for signal information generated by a strategy.

    This is an intermediate representation before creating the DB model.
    """

    symbol: str
    signal_type: SignalType
    strength: Decimal  # 0.0 to 1.0
    confidence: Decimal  # 0.0 to 1.0
    price_at_signal: Decimal
    entry_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    risk_reward_ratio: Decimal | None = None
    indicators: dict | None = None
    notes: str | None = None

    def to_dict(self) -> dict:
        """Convert SignalData to dictionary."""
        return {
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": float(self.strength),
            "confidence": float(self.confidence),
            "price_at_signal": float(self.price_at_signal),
            "entry_price": float(self.entry_price) if self.entry_price else None,
            "stop_loss": float(self.stop_loss) if self.stop_loss else None,
            "take_profit": float(self.take_profit) if self.take_profit else None,
            "risk_reward_ratio": float(self.risk_reward_ratio) if self.risk_reward_ratio else None,
            "indicators": self.indicators,
            "notes": self.notes,
        }

